name: Setup test configuration file
description: Shared test environment setup.
# This action takes few inputs and generate a JSON configuration file
# suitable for GO driver tests.

inputs:
  configuration-content:
    required: true
  configuration-file:
    required: false
    default: "${{ github.workspace }}/go-driver-config.json"
  database-version:
    required: true
  database-host:
    required: true
  database-service:
    required: true
  database-user:
    required: true
  database-password:
    required: true

runs:
  using: composite
  steps:
    - name: Write config to file
      shell: bash
      run: |
        echo -n  "${{ inputs.configuration-content }}" \
          | sed \
              -e "s/TEST_DB_VERSION/${{ inputs.database-version }}/g" \
              -e "s/TEST_DB_SERVICE/${{ inputs.database-service }}/g" \
              -e "s/TEST_DB_HOST/${{ inputs.database-host }}/g" \
              -e "s/TEST_DB_USER/${{ inputs.database-user }}/g" \
              -e "s/TEST_DB_PASSWORD/${{ inputs.database-password }}/g" \
          > "${{ inputs.configuration-file }}"
        cat  ${{ inputs.configuration-file }}
