name: Setup test configuration file
description: Shared test environment setup.
# This action takes few inputs and generate a JSON configuration file
# suitable for GO driver tests.

inputs:
  configuration-file:
    required: false
    default: "${{ github.workspace }}/go-driver-config.json"
  database-version:
    required: true
  database-host:
    required: true
  database-service:
    required: true
  database-user:
    required: true
  database-password:
    required: true
  database-protocol:
    required: true
  database-port:
    required: true

runs:
  using: composite
  steps:
    - name: Write config to file
      shell: bash
      env:
       GO_DRIVER_CONFIGURATIONS: |-
        [
         {
           "\"config_name\"": "\"pipeline_test\"",
           "\"enabled\"": true,
           "\"database_version\"": TEST_DB_VERSION,
           "\"driver\"": {
             "\"name\"": "\"oracledb\""
           },
           "\"database\"": {
             "\"host\"": TEST_DB_HOST,
             "\"port\"": TEST_DB_PORT,
             "\"servicename\"": TEST_DB_SERVICE,
             "\"protocol\"": TEST_DB_PROTOCOL
           },
           "\"credentials"\": {
             "\"username"\": TEST_DB_USER,
             "\"password"\": TEST_DB_PASSWORD
           }
         }
        ]
      run: |
        echo -n  "${{ env.GO_DRIVER_CONFIGURATIONS }}" \
          | sed \
              -e "s/TEST_DB_VERSION/\"${{ inputs.database-version }}\"/g" \
              -e "s/TEST_DB_SERVICE/\"${{ inputs.database-service }}\"/g" \
              -e "s/TEST_DB_HOST/\"${{ inputs.database-host }}\"/g" \
              -e "s/TEST_DB_USER/\"${{ inputs.database-user }}\"/g" \
              -e "s/TEST_DB_PASSWORD/\"${{ inputs.database-password }}\"/g" \
              -e "s/TEST_DB_PORT/${{ inputs.database-port }}/g" \
              -e "s/TEST_DB_PROTOCOL/\"${{ inputs.database-protocol }}\"/g" \
          > "${{ inputs.configuration-file }}"
        cat ${{ inputs.configuration-file }}
