name: functional-validation
on:
  schedule:
    - cron: '0 1 * * 1-5'
      timezone: "America/New_York"
      inputs:
        branch:
          description: Branch name
          required: false
          default: main
          type: string

  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string

env:
  ORACLE_DRIVER_MODULE: "github.com/oracle/go-oracledb/v26/oracle"
  VALIDATION_USER_NAME: ogd_test_user

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  functional_validate_driver:
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - rdbms: base-database-service-19c
          - rdbms: base-database-service-21c
          - rdbms: base-database-service-26ai
          - rdbms: autonomous-transaction-processing-serverless-19c
          - rdbms: autonomous-transaction-processing-serverless-26ai
          - rdbms: base-database-service-26ai-rac
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1r
      - uses: ./.github/actions/setup-go-env
      - name: Create test database
        id: create_database
        uses: oracle-actions/setup-testpilot@ad55a0d7294112c44a9cc9a38f4b3d293da8fcf0 # 1.0.31
        with:
          oci-service: ${{ matrix.rdbms }}
          action: create
          user: ${{ env.VALIDATION_USER_NAME }}
          fully-qualified-names: true
      - uses: ./.github/actions/setup-test-configuration
        with:
          database-version: ${{ steps.create_database.outputs.database_version }}
          database-service: ${{ steps.create_database.outputs.database_service }}
          database-host: ${{ steps.create_database.outputs.database_host }}
          database-port: ${{ steps.create_database.outputs.database_port }}
          database-protocol: ${{ steps.create_database.outputs.database_protocol }}
          database-user: ${{ steps.create_database.outputs.database_user }}
          database-password: ${{ steps.create_database.outputs.database_password }}
      - run: |
          go test -parallel=10  -shuffle=on -v $(go list ./... | grep -v /vendor/ | grep -v go-driver/examples ) -coverpkg=./... -cover -run TestCategoryExecutor -coverprofile=${{ github.workspace }}/coverage-results.out -driver.config.filename=${{ github.workspace }}/go-driver-config.json -driver.config.name=pipeline_test  -test.category="functional"
#          awk 'BEGIN{min=80} /^mode:/ {next} {split($1,a,":"); f=a[1]; s=$2+0; c=$3+0; total[f]+=s; all+=s; if(c>0){covered[f]+=s; cov+=s}} END{for(f in total) printf "%s %.1f%%\n", f, 100*covered[f]/total[f]; pct=all?100*cov/all:0; printf "total: %.1f%%\n", pct; exit(pct>=min?0:1)}' ${{ github.workspace }}/coverage-results.out
      - uses: oracle-actions/setup-testpilot@ad55a0d7294112c44a9cc9a38f4b3d293da8fcf0 # 1.0.31
        if: always()
        with:
          oci-service: ${{ matrix.rdbms }}
          action: delete
          user: ${{ env.VALIDATION_USER_NAME }}

  bench_driver:
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    strategy:
      matrix:
        include:
          - rdbms: base-database-service-26ai
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go-env
      - name: Create test database
        id: create_database
        uses: oracle-actions/setup-testpilot@ad55a0d7294112c44a9cc9a38f4b3d293da8fcf0 # 1.0.31
        with:
          oci-service: ${{ matrix.rdbms }}
          action: create
          user: ${{ env.VALIDATION_USER_NAME }}
          fully-qualified-names: true
      - uses: ./.github/actions/setup-test-configuration
        with:
          database-version: ${{ steps.create_database.outputs.database_version }}
          database-service: ${{ steps.create_database.outputs.database_service }}
          database-host: ${{ steps.create_database.outputs.database_host }}
          database-port: ${{ steps.create_database.outputs.database_port }}
          database-protocol: ${{ steps.create_database.outputs.database_protocol }}
          database-user: ${{ steps.create_database.outputs.database_user }}
          database-password: ${{ steps.create_database.outputs.database_password }}
      - run: go test -v $(go list ${{ github.workspace }}/oracle/... | egrep -v /vendor/) -run=^$ -bench=. -benchmem -benchtime=10x -driver.config.filename=${{ github.workspace }}/go-driver-config.json -driver.config.name=pipeline_test
      - uses: oracle-actions/setup-testpilot@ad55a0d7294112c44a9cc9a38f4b3d293da8fcf0 # 1.0.31
        if: always()
        with:
          oci-service: ${{ matrix.rdbms }}
          action: delete
          user: ${{ env.VALIDATION_USER_NAME }}

