name: functional-validation
on:
  schedule:
    - cron: '0 1 * * 1-5'
      timezone: "America/New_York"
      inputs:
        branch:
          description: Branch name
          required: false
          default: main
          type: string

  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string

env:
  ORACLE_DRIVER_MODULE: "github.com/oracle/go-driver/oracle"
  VALIDATION_USER_NAME: ogd_test_user
  VALIDATION_USER_PASSWORD: tiger
  GO_DRIVER_CONFIGURATIONS: |-
    [
      {
        "config_name": "pipeline_test",
        "enabled": true,
        "database_version": 26,
        "driver": {
          "name": "oraclego"
        },
        "database": {
          "host": "localhost",
          "port": 1521,
          "servicename": "FREEPDB1",
          "protocol": "tcp"
        },
        "credentials": {
          "username": "ogd_test_user",
          "password": "tiger"
        }
      }
    ]
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:

  functional_validate_driver:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go-env
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: ${VALIDATION_USER_NAME}
          app-user-password: ${VALIDATION_USER_PASSWORD}
          container-name: oracledb
      - name: Write config to file
        shell: bash
        run: |
          printf '%s' "$GO_DRIVER_CONFIGURATIONS" > ${{ github.workspace }}/go-driver-config.json
      - run: go test -parallel=10  -shuffle=on -v $ORACLE_DRIVER_MODULE -run TestCategoryExecutor -driver.config.filename=${{ github.workspace }}/go-driver-config.json -driver.config.name=pipeline_test  -test.category="functional"

  bench_driver:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go-env
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: ${VALIDATION_USER_NAME}
          app-user-password: ${VALIDATION_USER_PASSWORD}
          container-name: oracledb
      - name: Write config to file
        shell: bash
        run: |
          printf '%s' "$GO_DRIVER_CONFIGURATIONS" > ${{ github.workspace }}/go-driver-config.json
      - run: go test -parallel=10  -shuffle=on -v $(go list ${{ github.workspace }}/oracle/... | egrep -v /vendor/) -run=^$ -bench=. -benchmem -benchtime=10x -driver.config.filename=${{ github.workspace }}/go-driver-config.json -driver.config.name=pipeline_test


